#!/bin/bash
#      .-.     .-.     .-.     .-.     .-.     .-.     .-.     .-.     .-.
# `._.'   `._.'   `._.'   `._.'   `._.'   `._.'   `._.'   `._.'   `._.'   `._.'
#
# github.com/rafi ~/.profile

source "$HOME/.config/bash/exports"
source "$HOME/.bashrc"

#if [ -n "$IS_SSH" ]; then
#	hash tmux 2>/dev/null && tmux has 2>/dev/null && exec tmux attach
#fi
