#!/usr/bin/env bash
#      .-.     .-.     .-.     .-.     .-.     .-.
# `._.'   `._.'   `._.'   `._.'   `._.'   `._.'   `
#
# github.com/rafi/.config bash/profile

source "$HOME/.config/bash/exports"
source "$XDG_CONFIG_HOME/bash/bashrc"

# If SSH session and not running tmux, list tmux sessions on log-in.
if [ -n "$SSH_TTY" ] && [ -z "$TMUX" ] && hash tmux 2>/dev/null; then
	tmux list-sessions 2>/dev/null | sed 's/^/# tmux /'
fi

# vim: set ft=sh ts=2 sw=0 tw=80 noet :
